name: Ping Hugging Face Space

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the Space
        run: curl -s https://oex2003-ain8n.hf.space/ > /dev/null
